# Source: unguard/templates/profile-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unguard-profile-service
  labels:
    app.kubernetes.io/name: profile-service
    app.kubernetes.io/part-of: unguard
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: profile-service
      app.kubernetes.io/part-of: unguard
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: profile-service
        app.kubernetes.io/part-of: unguard
    spec:
      containers:
      - name: profile-service
        image: ghcr.io/dynatrace-oss/unguard/unguard-profile-service:0.9.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 15
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:h2:file:./database/bio"
        - name: SPRING_DATASOURCE_USERNAME
          value: "sa"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "password"
        - name: OTEL_LOGS_EXPORTER
          value: "none"
        - name: OTEL_METRICS_EXPORTER
          value: "none"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=unguard-profile-service"
        - name: OTEL_TRACES_EXPORTER
          value: "none"
        securityContext:
          runAsUser: 1000
